# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Diff infrastructure and add as PR comment

on:
  pull_request:
    branches: [ $default-branch ]

jobs:
  aws-cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          # cache: 'yarn'
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      
      - name: Install dependencies
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_READ_TOKEN }}

      - name: Add comment to PR
        uses: actions/github-script@v5
        with:
          script: |
            const util = require('util');
            const execPromise = util.promisify(require('child_process').exec);
            const { stdout, stderr } = await execPromise('yarn --silent deploy:diff');
            const stacks = stderr.split('\nStack ');
            stacks.shift();
            const diff = stacks.map((stack) => {
              let lines = stack.split('\n');
              const title = lines.shift();
              lines = lines.map(line => line.replace('[+]', '✅')
                .replace('[-]', '🅾️')
                .replace('│ - │', '|🅾️|')
                .replace('│ + │', '|✅|')
                .replace('[ ]', '🆗')
                .replace('There were no differences', '🤷🏼 There were no differences 😴😴')
                .replace('IAM Statement Changes', '🛂 IAM Statement Changes')
                .replace('IAM Policy Changes', '🛅 IAM Policy Changes')
                .replace('Resources', '🥞 Resources')
                .replace('[~]', '☢️'));
              lines.unshift('```');
              lines.push('```');              
              return `## Stack ${title}\n${lines.join('\n')}`;
            }).join('\n---\n');
            try {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: diff,
              });
            } catch(err) {  };
